# Generated by Django 4.0.6 on 2022-08-03 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200118_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='is_patient',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='is_doctor',
        ),
    ]
