# Generated by Django 4.0.6 on 2022-08-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_doctor_is_patient_remove_patient_is_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_patient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
