# Generated by Django 4.0.6 on 2022-08-03 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_doctor_is_doctor_doctor_is_patient_patient_is_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='State_Medical_Council',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='rating',
        ),
        migrations.DeleteModel(
            name='rating_review',
        ),
    ]
